/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author YANUAREKA
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    private Connection conn;
    private ResultSet rs;
    private PreparedStatement pStm;
    
    public Dashboard() {
        initComponents();
        conn = Koneksi.getConnection();
        
        hitungDataAnggota();
        hitungBuku();
        hitungPeminjaman();
        hitungPengembalian();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCustom1 = new table.TableCustom();
        pn_dashboard = new javax.swing.JPanel();
        cardAnggota = new javax.swing.JPanel();
        lb_anggota = new javax.swing.JLabel();
        lg_iconAnggota = new javax.swing.JLabel();
        lb_jmlAnggota = new javax.swing.JLabel();
        cardBuku = new javax.swing.JPanel();
        lb_buku = new javax.swing.JLabel();
        lg_iconBuku = new javax.swing.JLabel();
        lb_jmlBuku = new javax.swing.JLabel();
        cardAnggota2 = new javax.swing.JPanel();
        lb_anggota2 = new javax.swing.JLabel();
        lg_iconAnggota2 = new javax.swing.JLabel();
        lb_jmlPeminjaman = new javax.swing.JLabel();
        cardAnggota3 = new javax.swing.JPanel();
        lb_anggota3 = new javax.swing.JLabel();
        lg_iconAnggota3 = new javax.swing.JLabel();
        lb_jmlPengembalian = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        pn_dashboard.setBackground(new java.awt.Color(255, 255, 255));

        cardAnggota.setBackground(new java.awt.Color(236, 239, 241));
        cardAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardAnggota.setPreferredSize(new java.awt.Dimension(230, 125));

        lb_anggota.setBackground(new java.awt.Color(102, 102, 102));
        lb_anggota.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lb_anggota.setForeground(new java.awt.Color(153, 153, 153));
        lb_anggota.setText("Anggota");

        lg_iconAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/People_1.png"))); // NOI18N

        lb_jmlAnggota.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lb_jmlAnggota.setForeground(new java.awt.Color(102, 102, 102));
        lb_jmlAnggota.setText("0");

        javax.swing.GroupLayout cardAnggotaLayout = new javax.swing.GroupLayout(cardAnggota);
        cardAnggota.setLayout(cardAnggotaLayout);
        cardAnggotaLayout.setHorizontalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_anggota)
                    .addComponent(lb_jmlAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lg_iconAnggota)
                .addGap(31, 31, 31))
        );
        cardAnggotaLayout.setVerticalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_anggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_jmlAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lg_iconAnggota)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cardBuku.setBackground(new java.awt.Color(236, 239, 241));
        cardBuku.setForeground(new java.awt.Color(153, 153, 153));
        cardBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardBuku.setPreferredSize(new java.awt.Dimension(235, 125));

        lb_buku.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lb_buku.setForeground(new java.awt.Color(153, 153, 153));
        lb_buku.setText("Buku");

        lg_iconBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Book.png"))); // NOI18N

        lb_jmlBuku.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lb_jmlBuku.setForeground(new java.awt.Color(102, 102, 102));
        lb_jmlBuku.setText("0");

        javax.swing.GroupLayout cardBukuLayout = new javax.swing.GroupLayout(cardBuku);
        cardBuku.setLayout(cardBukuLayout);
        cardBukuLayout.setHorizontalGroup(
            cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBukuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_buku)
                    .addComponent(lb_jmlBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(lg_iconBuku)
                .addGap(31, 31, 31))
        );
        cardBukuLayout.setVerticalGroup(
            cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBukuLayout.createSequentialGroup()
                .addGroup(cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardBukuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_buku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_jmlBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardBukuLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lg_iconBuku)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardAnggota2.setBackground(new java.awt.Color(236, 239, 241));
        cardAnggota2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardAnggota2.setPreferredSize(new java.awt.Dimension(235, 125));

        lb_anggota2.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lb_anggota2.setForeground(new java.awt.Color(153, 153, 153));
        lb_anggota2.setText("Peminjaman");

        lg_iconAnggota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add Book_1.png"))); // NOI18N

        lb_jmlPeminjaman.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lb_jmlPeminjaman.setForeground(new java.awt.Color(102, 102, 102));
        lb_jmlPeminjaman.setText("0");

        javax.swing.GroupLayout cardAnggota2Layout = new javax.swing.GroupLayout(cardAnggota2);
        cardAnggota2.setLayout(cardAnggota2Layout);
        cardAnggota2Layout.setHorizontalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_anggota2)
                    .addComponent(lb_jmlPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lg_iconAnggota2)
                .addGap(31, 31, 31))
        );
        cardAnggota2Layout.setVerticalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addGroup(cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggota2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_anggota2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_jmlPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardAnggota2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lg_iconAnggota2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cardAnggota3.setBackground(new java.awt.Color(236, 239, 241));
        cardAnggota3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardAnggota3.setPreferredSize(new java.awt.Dimension(235, 125));

        lb_anggota3.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lb_anggota3.setForeground(new java.awt.Color(153, 153, 153));
        lb_anggota3.setText("Pengembalian");

        lg_iconAnggota3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Return Book_2.png"))); // NOI18N

        lb_jmlPengembalian.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lb_jmlPengembalian.setForeground(new java.awt.Color(102, 102, 102));
        lb_jmlPengembalian.setText("0");

        javax.swing.GroupLayout cardAnggota3Layout = new javax.swing.GroupLayout(cardAnggota3);
        cardAnggota3.setLayout(cardAnggota3Layout);
        cardAnggota3Layout.setHorizontalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_anggota3)
                    .addComponent(lb_jmlPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lg_iconAnggota3)
                .addGap(31, 31, 31))
        );
        cardAnggota3Layout.setVerticalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addGroup(cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggota3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_anggota3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_jmlPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardAnggota3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lg_iconAnggota3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Riwayat Peminjaman Buku");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Control Panel.png"))); // NOI18N
        jLabel2.setText("Master Data > Dashboard");

        javax.swing.GroupLayout pn_dashboardLayout = new javax.swing.GroupLayout(pn_dashboard);
        pn_dashboard.setLayout(pn_dashboardLayout);
        pn_dashboardLayout.setHorizontalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dashboardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(pn_dashboardLayout.createSequentialGroup()
                        .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_dashboardLayout.createSequentialGroup()
                                .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(cardBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(cardAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(cardAnggota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_dashboardLayout.setVerticalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardAnggota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cardBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        add(pn_dashboard, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardAnggota;
    private javax.swing.JPanel cardAnggota2;
    private javax.swing.JPanel cardAnggota3;
    private javax.swing.JPanel cardBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_anggota;
    private javax.swing.JLabel lb_anggota2;
    private javax.swing.JLabel lb_anggota3;
    private javax.swing.JLabel lb_buku;
    private javax.swing.JLabel lb_jmlAnggota;
    private javax.swing.JLabel lb_jmlBuku;
    private javax.swing.JLabel lb_jmlPeminjaman;
    private javax.swing.JLabel lb_jmlPengembalian;
    private javax.swing.JLabel lg_iconAnggota;
    private javax.swing.JLabel lg_iconAnggota2;
    private javax.swing.JLabel lg_iconAnggota3;
    private javax.swing.JLabel lg_iconBuku;
    private javax.swing.JPanel pn_dashboard;
    private table.TableCustom tableCustom1;
    // End of variables declaration//GEN-END:variables

    //Count data anggota pada db
    private void hitungDataAnggota() {
        String sql = "SELECT COUNT(nama_anggota) AS total_anggota FROM anggota";

        try {
            pStm = conn.prepareStatement(sql);
            rs = pStm.executeQuery();

            if (rs.next()) {
                int totalAnggota = rs.getInt("total_anggota");
                lb_jmlAnggota.setText(Integer.toString(totalAnggota));
            }

            rs.close();
            pStm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //Count data buku pada db
    private void hitungBuku(){
        String sql = "SELECT COUNT(judul_buku) AS total_buku FROM buku";
        
        try {
            pStm = conn.prepareStatement(sql);
            rs = pStm.executeQuery();
            
            if(rs.next()){
                int totalBuku = rs.getInt("total_buku");
                lb_jmlBuku.setText(Integer.toString(totalBuku));
            }
            
            rs.close();
            pStm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //Count data peminjaman pada db
    private void hitungPeminjaman(){
        String sql = "SELECT COUNT(id_peminjaman) AS total_peminjaman FROM peminjaman";
        
        try {
            pStm = conn.prepareStatement(sql);
            rs = pStm.executeQuery();
            
            if(rs.next()){
                int totalPeminjaman = rs.getInt("total_peminjaman");
                lb_jmlPeminjaman.setText(Integer.toString(totalPeminjaman));
            }
            
            rs.close();
            pStm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //Count data pengembalian pada db
    private void hitungPengembalian(){
        String sql = "SELECT COUNT(id_pengembalian) AS total_pengembalian FROM pengembalian";
        
        try {
            pStm = conn.prepareStatement(sql);
            rs = pStm.executeQuery();
            
            if(rs.next()){
                int totalPengembalian = rs.getInt("total_pengembalian");
                lb_jmlPengembalian.setText(Integer.toString(totalPengembalian));
            }
            
            rs.close();
            pStm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
