/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author ARIM
 */
import Config.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import table.TableCustom;

public class DataBuku extends javax.swing.JDialog {

    private Connection conn;

    private String idBuku;
    private String judulBuku;
    private String pengarangBuku;
    private String penerbitBuku;
    
    //Getter
    public String getIdBuku() {
        return idBuku;
    }
    public String getJudulBuku() {
        return judulBuku;
    }
    public String getPengarangBuku() {
        return pengarangBuku;
    }
    public String getPenerbitBuku() {
        return penerbitBuku;
    }
    
    
    
    public DataBuku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Set table custom
        tableCustom2.apply(jScrollPane1, TableCustom.TableType.DEFAULT);

        conn = Koneksi.getConnection();
        setTableModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCustom2 = new table.TableCustom();
        pn_view = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pn_view.setBackground(new java.awt.Color(255, 255, 255));

        tblData.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Judul Buku", "Pengarang", "Tahun", "Id Kategori", "Nama Kategori", "Id Penerbit", "Nama Penerbit", "Stok", "Gambar"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Books.png"))); // NOI18N
        jLabel1.setText("Data Buku Perpustakaan");

        searchTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        searchTf.setForeground(new java.awt.Color(153, 153, 153));
        searchTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTfKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Cari");

        javax.swing.GroupLayout pn_viewLayout = new javax.swing.GroupLayout(pn_view);
        pn_view.setLayout(pn_viewLayout);
        pn_viewLayout.setHorizontalGroup(
            pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_viewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                    .addGroup(pn_viewLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_viewLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTf)))
                .addGap(15, 15, 15))
        );
        pn_viewLayout.setVerticalGroup(
            pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_viewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1082, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pn_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTfKeyReleased
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_searchTfKeyReleased

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        pilihData();
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataBuku dialog = new DataBuku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_view;
    private javax.swing.JTextField searchTf;
    private table.TableCustom tableCustom2;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        getData((DefaultTableModel) tblData.getModel());
    }
    
    //Set model
    private void setTableModel() {
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
    }

    
    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        
        try {
            String sql = "SELECT bk.id_buku, bk.judul_buku, bk.pengarang_buku, bk.tahun_terbit,\n" +
                        "kt.id_kategori, kt.nama_kategori,\n" +
                        "pn.id_penerbit, pn.nama_penerbit, bk.stok, bk.gambar\n" +
                        "FROM buku bk\n" +
                        "INNER JOIN kategori kt ON kt.id_kategori = bk.id_kategori\n" +
                        "INNER JOIN penerbit pn ON pn.id_penerbit = bk.id_penerbit ORDER BY bk.id_buku ASC";
            PreparedStatement pStm = conn.prepareStatement(sql);
            
            ResultSet rs = pStm.executeQuery(sql);
            
            while(rs.next()) {
                String idBuku = rs.getString("id_buku");
                String judulBuku = rs.getString("judul_buku");
                String pengarangBuku = rs.getString("pengarang_buku");
                String tahunTerbitBuku = rs.getString("tahun_terbit");
                String idKategori = rs.getString("id_kategori");
                String namaKategori = rs.getString("nama_kategori");
                String idPenerbit = rs.getString("id_penerbit");
                String namaPenerbit = rs.getString("nama_penerbit");
                String stokBuku = rs.getString("stok");
                String pathGambar = rs.getString("gambar");
                
                //Get image
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(pathGambar).getImage().getScaledInstance(70, 90, Image.SCALE_SMOOTH));
                
                Object[] getDataBuku = {
                    idBuku,
                    judulBuku,
                    pengarangBuku,
                    tahunTerbitBuku,
                    idKategori,
                    namaKategori,
                    idPenerbit,
                    namaPenerbit,
                    stokBuku,
                    imageIcon
                };
                model.addRow(getDataBuku);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Gagal" + e.getMessage());
        }
        
        //Render image ke tabel
        tblData.getColumnModel().getColumn(9).setCellRenderer(new ImageRenderer());
    }
    
    //Render image
    private class ImageRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setIcon(null);
            
            table.setRowHeight(row, ((ImageIcon) value).getIconHeight());
            
            if (value instanceof ImageIcon) {
                setIcon((ImageIcon) value);
            }
            return this;
        }
    }
    
    private void searchData() {
        String keyword = searchTf.getText();
        
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0);
        
        try {
           String sql = "SELECT bk.id_buku, bk.judul_buku, bk.pengarang_buku, bk.tahun_terbit,\n" +
                        "kt.id_kategori, kt.nama_kategori,\n" +
                        "pn.id_penerbit, pn.nama_penerbit, bk.stok, bk.gambar\n" +
                        "FROM buku bk\n" +
                        "INNER JOIN kategori kt ON kt.id_kategori = bk.id_kategori\n" +
                        "INNER JOIN penerbit pn ON pn.id_penerbit = bk.id_penerbit WHERE " +
                        "bk.judul_buku LIKE ? OR bk.pengarang_buku LIKE ?";
            PreparedStatement pStm = conn.prepareStatement(sql);
            pStm.setString(1, "%" + keyword + "%");
            pStm.setString(2, "%" + keyword + "%");
            ResultSet rs = pStm.executeQuery();
            
            while(rs.next()) {
                String idBuku = rs.getString("id_buku");
                String judulBuku = rs.getString("judul_buku");
                String pengarangBuku = rs.getString("pengarang_buku");
                String tahunTerbitBuku = rs.getString("tahun_terbit");
                String idKategori = rs.getString("id_kategori");
                String namaKategori = rs.getString("nama_kategori");
                String idPenerbit = rs.getString("id_penerbit");
                String namaPenerbit = rs.getString("nama_penerbit");
                String stokBuku = rs.getString("stok");
                String pathGambar = rs.getString("gambar");
                
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(pathGambar).getImage().getScaledInstance(70, 90, Image.SCALE_SMOOTH));
                
                Object[] dataBuku = {
                    idBuku,
                    judulBuku,
                    pengarangBuku,
                    tahunTerbitBuku,
                    idKategori,
                    namaKategori,
                    idPenerbit,
                    namaPenerbit,
                    stokBuku,
                    imageIcon
                };
                model.addRow(dataBuku);
            }
        } catch (Exception e) {
            System.err.println("Gagal cari data" + e.getMessage());
        }
    }
    
    private void pilihData(){
        int row = tblData.getSelectedRow();
        
        idBuku = tblData.getValueAt(row, 0).toString();
        judulBuku = tblData.getValueAt(row, 1).toString();
        pengarangBuku = tblData.getValueAt(row, 2).toString();
        penerbitBuku = tblData.getValueAt(row, 7).toString();
        
        dispose();
    }
}
