/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author YANUAREKA
 */
import Config.Koneksi;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import table.TableCustom;
import com.formdev.flatlaf.FlatLightLaf;

public class Pengembalian extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    private Connection conn;
    private Statement stm;
    private PreparedStatement pStm;
    private ResultSet rs;
    
    private String userId;
    private String filename;
    
    public Pengembalian(String userId) {
        initComponents();
        
        FlatLightLaf.setup();
        //Set table costum
        tableCustom1.apply(jScrollPane1, TableCustom.TableType.DEFAULT);
        
        conn = Koneksi.getConnection();
        this.userId = userId;
        
        setTabelModel();
        setTableModelDetail();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        tableCustom1 = new table.TableCustom();
        pn_main = new javax.swing.JPanel();
        pn_view = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTambah = new rojerusan.RSMaterialButtonRectangle();
        searchTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnDetail = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataDetail = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnCloseDetail = new javax.swing.JLabel();
        pn_add = new javax.swing.JPanel();
        btnSave = new rojerusan.RSMaterialButtonRectangle();
        btnCancel = new rojerusan.RSMaterialButtonRectangle();
        lbImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        idTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tglAktualTf = new javax.swing.JTextField();
        idPeminjamanTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tglPinjamTf = new javax.swing.JTextField();
        tglKembaliTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idAnggotaTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnGetPeminjaman = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pengarangBukuTf = new javax.swing.JTextField();
        penerbitBukuTf = new javax.swing.JTextField();
        judulBukuTf = new javax.swing.JTextField();
        idBukuTf = new javax.swing.JTextField();
        lbInfoDenda = new javax.swing.JLabel();
        dendaTf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        namaAnggotaTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        dateChooser1.setForeground(new java.awt.Color(55, 71, 79));
        dateChooser1.setDateFormat("yyyy-MM-dd");
        dateChooser1.setTextRefernce(tglAktualTf);

        setLayout(new java.awt.CardLayout());

        pn_main.setBackground(new java.awt.Color(255, 255, 255));
        pn_main.setLayout(new java.awt.CardLayout());

        pn_view.setBackground(new java.awt.Color(255, 255, 255));

        tblData.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pengembalian", "Tanggal Dikembalikan", "Id Peminjaman", "Petugas"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Return Book_1.png"))); // NOI18N
        jLabel1.setText("Data Pengembalian Buku Perpustakaan");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Return Book_1.png"))); // NOI18N
        jLabel2.setText("Transaksi > Pengembalian");

        btnTambah.setBackground(new java.awt.Color(55, 71, 79));
        btnTambah.setText("tambah");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        searchTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        searchTf.setForeground(new java.awt.Color(153, 153, 153));
        searchTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTfKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Cari");

        tblDataDetail.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblDataDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pengembalian", "Id Buku", "Judul Buku", "Denda"
            }
        ));
        jScrollPane2.setViewportView(tblDataDetail);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Return Book_1.png"))); // NOI18N
        jLabel4.setText("Data Detail Pengembalian Buku Perpustakaan");

        btnCloseDetail.setBackground(new java.awt.Color(51, 51, 51));
        btnCloseDetail.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnCloseDetail.setForeground(new java.awt.Color(153, 153, 153));
        btnCloseDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseDetail.setText("X");
        btnCloseDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseDetail.setPreferredSize(new java.awt.Dimension(35, 35));
        btnCloseDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseDetailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailLayout.createSequentialGroup()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCloseDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_viewLayout = new javax.swing.GroupLayout(pn_view);
        pn_view.setLayout(pn_viewLayout);
        pn_viewLayout.setHorizontalGroup(
            pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_viewLayout.createSequentialGroup()
                .addGroup(pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_viewLayout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_viewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pn_viewLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_viewLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pn_viewLayout.setVerticalGroup(
            pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_viewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_viewLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_main.add(pn_view, "card2");

        pn_add.setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(55, 71, 79));
        btnSave.setText("simpan");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setText("kembali");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lbImage.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add Book.png"))); // NOI18N
        lbImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("ID");

        idTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        idTf.setForeground(new java.awt.Color(153, 153, 153));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal");

        tglAktualTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        tglAktualTf.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglAktualTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tglAktualTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        idPeminjamanTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        idPeminjamanTf.setForeground(new java.awt.Color(153, 153, 153));
        idPeminjamanTf.setText("Id Peminjaman");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Peminjaman");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setText("Tgl Pinjam");

        tglPinjamTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        tglPinjamTf.setForeground(new java.awt.Color(153, 153, 153));
        tglPinjamTf.setText("Tanggal Peminjaman");

        tglKembaliTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        tglKembaliTf.setForeground(new java.awt.Color(153, 153, 153));
        tglKembaliTf.setText("Tanggal Pengembalian");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setText("Tgl Kembali");

        idAnggotaTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        idAnggotaTf.setForeground(new java.awt.Color(153, 153, 153));
        idAnggotaTf.setText("Id Anggota");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setText("Id Anggota");

        btnGetPeminjaman.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnGetPeminjaman.setForeground(new java.awt.Color(204, 204, 204));
        btnGetPeminjaman.setText("...");
        btnGetPeminjaman.setPreferredSize(new java.awt.Dimension(35, 35));
        btnGetPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPeminjamanActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setText("Buku");

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setText("Judul");

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel16.setText("Pengarang");

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setText("Penerbit");

        pengarangBukuTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        pengarangBukuTf.setForeground(new java.awt.Color(153, 153, 153));
        pengarangBukuTf.setText("Pengarang");

        penerbitBukuTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        penerbitBukuTf.setForeground(new java.awt.Color(153, 153, 153));
        penerbitBukuTf.setText("Penerbit");

        judulBukuTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        judulBukuTf.setForeground(new java.awt.Color(153, 153, 153));
        judulBukuTf.setText("Judul Buku");

        idBukuTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        idBukuTf.setForeground(new java.awt.Color(153, 153, 153));
        idBukuTf.setText("Id");

        lbInfoDenda.setFont(new java.awt.Font("Poppins", 2, 18)); // NOI18N
        lbInfoDenda.setForeground(new java.awt.Color(204, 204, 204));
        lbInfoDenda.setText("Info Denda");

        dendaTf.setFont(new java.awt.Font("Poppins", 2, 18)); // NOI18N
        dendaTf.setForeground(new java.awt.Color(153, 153, 153));
        dendaTf.setPreferredSize(new java.awt.Dimension(60, 35));

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel19.setText("Denda");

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel20.setText("Nama Anggota");

        namaAnggotaTf.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        namaAnggotaTf.setForeground(new java.awt.Color(153, 153, 153));
        namaAnggotaTf.setText("Nama Anggota");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Return Book_1.png"))); // NOI18N
        jLabel5.setText("Tambah Data Pengembalian Buku Perpustakaan");

        javax.swing.GroupLayout pn_addLayout = new javax.swing.GroupLayout(pn_add);
        pn_add.setLayout(pn_addLayout);
        pn_addLayout.setHorizontalGroup(
            pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_addLayout.createSequentialGroup()
                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_addLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pn_addLayout.createSequentialGroup()
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_addLayout.createSequentialGroup()
                                        .addComponent(idPeminjamanTf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGetPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tglPinjamTf)
                                    .addComponent(tglKembaliTf, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(idAnggotaTf)
                                    .addComponent(namaAnggotaTf))
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_addLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(penerbitBukuTf)
                                            .addComponent(pengarangBukuTf, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                            .addComponent(judulBukuTf)
                                            .addComponent(idBukuTf))
                                        .addGap(30, 30, 30)
                                        .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_addLayout.createSequentialGroup()
                                        .addGap(503, 503, 503)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbInfoDenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dendaTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(pn_addLayout.createSequentialGroup()
                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_addLayout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_addLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_addLayout.setVerticalGroup(
            pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_addLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_addLayout.createSequentialGroup()
                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_addLayout.createSequentialGroup()
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idPeminjamanTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(btnGetPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tglPinjamTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tglKembaliTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(idAnggotaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_addLayout.createSequentialGroup()
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_addLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_addLayout.createSequentialGroup()
                                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idBukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(judulBukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pengarangBukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(penerbitBukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(namaAnggotaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dendaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbInfoDenda))
                    .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_main.add(pn_add, "card2");

        add(pn_main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        pn_main.removeAll();
        pn_main.add(pn_add);
        pn_main.repaint();
        pn_main.revalidate();
        
        idTf.setText(setIdPengembalian());
    }//GEN-LAST:event_btnTambahActionPerformed
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        pn_main.removeAll();
        pn_main.add(pn_view);
        pn_main.repaint();
        pn_main.revalidate();
        
        showPanelView();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        insertData();
        insertDataDetail();
        updateStatus();
        resetForm();
        loadData();
        showPanelView();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void searchTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTfKeyTyped
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_searchTfKeyTyped

    private void btnGetPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPeminjamanActionPerformed
        // TODO add your handling code here:
        getPeminjaman();
        hitungDenda();
    }//GEN-LAST:event_btnGetPeminjamanActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        pnDetail.setVisible(true);
        int row = tblData.getSelectedRow();
        String id = tblData.getValueAt(row, 0).toString();
        
        getDataDetail((DefaultTableModel) tblDataDetail.getModel(), id);
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnCloseDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseDetailMouseClicked
        // TODO add your handling code here:
        showPanelView();
        loadData();
    }//GEN-LAST:event_btnCloseDetailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnCancel;
    private javax.swing.JLabel btnCloseDetail;
    private javax.swing.JButton btnGetPeminjaman;
    private rojerusan.RSMaterialButtonRectangle btnSave;
    private rojerusan.RSMaterialButtonRectangle btnTambah;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JTextField dendaTf;
    private javax.swing.JTextField idAnggotaTf;
    private javax.swing.JTextField idBukuTf;
    private javax.swing.JTextField idPeminjamanTf;
    private javax.swing.JTextField idTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField judulBukuTf;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbInfoDenda;
    private javax.swing.JTextField namaAnggotaTf;
    private javax.swing.JTextField penerbitBukuTf;
    private javax.swing.JTextField pengarangBukuTf;
    private javax.swing.JPanel pnDetail;
    private javax.swing.JPanel pn_add;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_view;
    private javax.swing.JTextField searchTf;
    private table.TableCustom tableCustom1;
    private javax.swing.JTable tblData;
    private javax.swing.JTable tblDataDetail;
    private javax.swing.JTextField tglAktualTf;
    private javax.swing.JTextField tglKembaliTf;
    private javax.swing.JTextField tglPinjamTf;
    // End of variables declaration//GEN-END:variables

    //Set model
    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
    }
    
    private void loadData() {
        getData((DefaultTableModel) tblData.getModel());
        pnDetail.setVisible(false);
        lbInfoDenda.setVisible(false);
    }
    
    private void showPanelView(){
        pn_main.removeAll();
        pn_main.add(new Pengembalian(userId));
        pn_main.repaint();
        pn_main.revalidate();
    }
    
    private void resetForm() {
        idTf.setText("");
        tglAktualTf.setText("");
        idPeminjamanTf.setText("");
        tglPinjamTf.setText("");
        tglKembaliTf.setText("");
        idAnggotaTf.setText("");
        namaAnggotaTf.setText("");
        idBukuTf.setText("");
        judulBukuTf.setText("");
        pengarangBukuTf.setText("");
        penerbitBukuTf.setText("");
        dendaTf.setText("");
        
        ImageIcon defaultIcon = new ImageIcon(getClass().getResource("/Img/Add Book.png"));
        lbImage.setIcon(defaultIcon);
    }

    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        try {
            String sql = "SELECT *\n" +
                            "FROM pengembalian pnb\n" +
                            "INNER JOIN peminjaman pmj ON pmj.id_peminjaman = pnb.id_peminjaman\n" +
                            "INNER JOIN user usr ON usr.id_user = pnb.id_user ORDER BY pnb.id_pengembalian ASC";
            
            pStm = conn.prepareStatement(sql);
            ResultSet rs = pStm.executeQuery(sql);
            
            while(rs.next()) {
                String idPengembalian = rs.getString("id_pengembalian");
                String tanggalDikembalikan = rs.getString("tanggal_dikembalikan");
                String idPeminjaman = rs.getString("id_peminjaman");
                String namaUser = rs.getString("nama_user");
                
                Object[] dataPeminjaman = {
                    idPengembalian,
                    tanggalDikembalikan,
                    idPeminjaman,
                    namaUser
                };
                model.addRow(dataPeminjaman);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Gagal" + e.getMessage());
        }
    }

    private void setTableModelDetail(){
        DefaultTableModel model = (DefaultTableModel) tblDataDetail.getModel();
    }
    
    private void getDataDetail(DefaultTableModel model, String id) {
        model.setRowCount(0);
        try {
            String sql = "SELECT pnb.id_pengembalian, bk.id_buku, bk.judul_buku, pnb.jumlah_denda\n" +
                            "FROM detail_pengembalian pnb\n" +
                            "INNER JOIN buku bk ON bk.id_buku = pnb.id_buku\n" +
                            "WHERE pnb.id_pengembalian ='"+id+"'" +
                            "ORDER BY pnb.id_pengembalian ASC";
            
            pStm = conn.prepareStatement(sql);
            ResultSet rs = pStm.executeQuery(sql);
            
            while(rs.next()) {
                String idPengembalian = rs.getString("id_pengembalian");
                String idBuku = rs.getString("id_buku");
                String judulBuku = rs.getString("judul_buku");
                double jumlahDenda = rs.getDouble("jumlah_denda");
                
                Object[] dataDetailPengembalian = {
                    idPengembalian,
                    idBuku,
                    judulBuku,
                    Math.round(jumlahDenda)
                };
                model.addRow(dataDetailPengembalian);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Gagal" + e.getMessage());
        }
    }
    
    private String setIdPengembalian() {
        String urut = null;
        Date now = new Date();
        SimpleDateFormat noFormat = new SimpleDateFormat("yyMM");
        String no = noFormat.format(now);
        
        String sql = "SELECT RIGHT (id_pengembalian, 3) AS Nomor " +
                "FROM pengembalian " + 
                "WHERE id_pengembalian LIKE 'PNB" + no + "%' " +
                "ORDER BY id_pengembalian DESC " +
                "LIMIT 1";
        
        try {
            stm = conn.prepareStatement(sql);
            rs = stm.executeQuery(sql);
            
            if(rs.next()) {
                int nomor = Integer.parseInt(rs.getString("Nomor")) + 1;
                urut = "PNB" + no + String.format("%03d", nomor);
            } else {
                urut = "PNB" + no + "001";
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Set Id GAGAL" + e.getMessage());
        }
        return urut;
    }
    
    private void getPeminjaman() {
        boolean closeable = true;
        DataPeminjaman pmj = new DataPeminjaman(null, closeable);
        pmj.setVisible(true);
        
        String id = pmj.getIdBuku();
        
        idPeminjamanTf.setText(pmj.getIdPeminjaman());
        tglPinjamTf.setText(pmj.getTanggalPinjam());
        tglKembaliTf.setText(pmj.getTanggalKembali());
        idAnggotaTf.setText(pmj.getIdAnggota());
        namaAnggotaTf.setText(pmj.getNamaAnggota());
        idBukuTf.setText(pmj.getIdBuku());
        judulBukuTf.setText(pmj.getJudulBuku());
        pengarangBukuTf.setText(pmj.getPengarangBuku());
        penerbitBukuTf.setText(pmj.getPenerbitBuku());
        
        setImage(lbImage, id);
        
        idPeminjamanTf.setEnabled(false);
        tglPinjamTf.setEnabled(false);
        tglKembaliTf.setEnabled(false);
        idAnggotaTf.setEnabled(false);
        namaAnggotaTf.setEnabled(false);
        idBukuTf.setEnabled(false);
        judulBukuTf.setEnabled(false);
        pengarangBukuTf.setEnabled(false);
        penerbitBukuTf.setEnabled(false);
    }
    
    //Hitung denda pengembalian buku
    private void hitungDenda() {
        int dendaPerhari = 1000;
        String tanggalKembaliAktual = tglAktualTf.getText();
        String tanggalKembali = tglKembaliTf.getText();
        
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggalAktual = dateFormat.parse(tanggalKembaliAktual);
            Date tanggalDikembalikan = dateFormat.parse(tanggalKembali);
            
            long selisihHari = (tanggalAktual.getTime() - tanggalDikembalikan.getTime()) / (24 * 60 * 60 * 1000);
            int denda = (int) (selisihHari * dendaPerhari);
            dendaTf.setText(Integer.toString(denda));
            
            if(denda > 0) {
                lbInfoDenda.setVisible(true);
                lbInfoDenda.setText("Telat : "+ selisihHari + " hari");
            } else {
                lbInfoDenda.setText("Tidak Ada Denda");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void insertData() {
        String idPengembalian = idTf.getText();
        String tanggalAktual = tglAktualTf.getText();
        String idPeminjaman = idPeminjamanTf.getText();
        
        try {
            String sql = "INSERT INTO pengembalian (id_pengembalian, tanggal_dikembalikan, id_peminjaman, id_user) values (?,?,?,?)";
            pStm = conn.prepareStatement(sql);
            pStm.setString(1, idPengembalian);
            pStm.setString(2, tanggalAktual);
            pStm.setString(3, idPeminjaman);
            pStm.setString(4, userId);
            
            
            int rowInsertData = pStm.executeUpdate();
            if(rowInsertData > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Data gagal ditambahkan" + e.getMessage());
        }
    }
    
    private void insertDataDetail() {
        String idPengembalian = idTf.getText();
        String idBuku = idBukuTf.getText();
        String jumlahDenda = dendaTf.getText();
        
        try {
            String sql = "INSERT INTO detail_pengembalian (id_pengembalian, id_buku, jumlah_denda) VALUES (?,?,?)";
            pStm = conn.prepareStatement(sql);
            pStm.setString(1, idPengembalian);
            pStm.setString(2, idBuku);
            pStm.setString(3, jumlahDenda);
            
            pStm.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Data gagal get detail" + e.getMessage());
        }
    }
    
    private void updateStatus(){
        String idPeminjaman = idPeminjamanTf.getText();
        String idBuku = idBukuTf.getText();
        String statusPeminjaman = "Sudah Dikembalikan";
        
        try {
            String sql = "UPDATE detail_peminjaman SET status_peminjaman=? WHERE id_peminjaman=? AND id_buku=?";
            pStm = conn.prepareStatement(sql);
            pStm.setString(1, statusPeminjaman);
            pStm.setString(2, idPeminjaman);
            pStm.setString(3, idBuku);
            
            pStm.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Data gagal ditambahkan" + e.getMessage());
        }
    }
    
    private void setImage(JLabel lb_gambar, String id) {
        try {
            String sql = "SELECT * FROM buku WHERE id_buku = '"+ id +"'";
            pStm = conn.prepareStatement(sql);
            rs = pStm.executeQuery();
            
            if(rs.next()) {
                String img = rs.getString("gambar");
                if(img != null) {
                    ImageIcon imageIcon = new ImageIcon( new ImageIcon(img).getImage()
                            .getScaledInstance(lb_gambar.getWidth(), lb_gambar.getHeight(), Image.SCALE_SMOOTH));
                    lb_gambar.setIcon(imageIcon);
                } else {
                    ImageIcon defaultIcon = new ImageIcon(getClass().getResource("Img/Add Book.png"));
                    lb_gambar.setIcon(defaultIcon);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Set image error " + e.getMessage());
        }
    }
    
    private void searchData() {
        String keyword = searchTf.getText();
        
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0);
        
        try {
           String sql = "SELECT pm.id_peminjaman, pm.tanggal_peminjaman, pm.tanggal_pengembalian, pm.total_pinjam, agt.nama_anggota, usr.nama_user\n" +
                            "FROM peminjaman pm\n" +
                            "INNER JOIN anggota agt ON agt.id_anggota = pm.id_anggota\n" +
                            "INNER JOIN user usr ON usr.id_user = pm.id_user\n" +
                            "WHERE pm.id_peminjaman LIKE ? OR agt.nama_anggota LIKE ?";
            pStm = conn.prepareStatement(sql);
            pStm.setString(1, "%" + keyword + "%");
            pStm.setString(2, "%" + keyword + "%");
            rs = pStm.executeQuery();
            
            while(rs.next()) {
                String idPeminjaman = rs.getString("id_peminjaman");
                String tanggalPinjam = rs.getString("tanggal_peminjaman");
                String tanggalKembali = rs.getString("tanggal_pengembalian");
                String totalPinjam = rs.getString("total_pinjam");
                String namaAnggota = rs.getString("nama_anggota");
                String namaUser = rs.getString("nama_user");
                
                Object[] dataPeminjaman = {
                    idPeminjaman,
                    tanggalPinjam,
                    tanggalKembali,
                    totalPinjam,
                    namaAnggota,
                    namaUser
                };
                model.addRow(dataPeminjaman);
            }
        } catch (Exception e) {
            System.err.println("Gagal cari data" + e.getMessage());
        }
    }

}
