/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import View.Anggota;
import View.Buku;
import View.Dashboard;
import View.Kategori;
import View.Penerbit;
import View.Petugas;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author YANUAREKA
 */
public class MasterData extends javax.swing.JPanel {

    /**
     * Creates new form MasterData
     */
    private MenuUtama1 menuUtama;
    
    public MasterData(MenuUtama1 menuUtama) {
        initComponents();
        this.menuUtama = menuUtama;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_master = new javax.swing.JLabel();
        pn_btnDashboard = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        pn_btnAnggota = new javax.swing.JPanel();
        pn_lineAnggota = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_anggota = new javax.swing.JLabel();
        pn_btnBuku = new javax.swing.JPanel();
        pn_lineBuku = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_buku = new javax.swing.JLabel();
        pn_btnKategori = new javax.swing.JPanel();
        pn_lineKategori = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_kategori = new javax.swing.JLabel();
        pn_btnPenerbit = new javax.swing.JPanel();
        pn_linePenerbit = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_penerbit = new javax.swing.JLabel();
        pn_btnPetugas = new javax.swing.JPanel();
        pn_linePetugas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_petugas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 239, 241));

        lb_master.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lb_master.setForeground(new java.awt.Color(204, 204, 204));
        lb_master.setText("Master Data");

        pn_btnDashboard.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnDashboard.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_line.setBackground(new java.awt.Color(236, 239, 241));
        pn_line.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Control Panel.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_dashboard.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(102, 102, 102));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dashboard.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnDashboardLayout = new javax.swing.GroupLayout(pn_btnDashboard);
        pn_btnDashboard.setLayout(pn_btnDashboardLayout);
        pn_btnDashboardLayout.setHorizontalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnDashboardLayout.setVerticalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_btnAnggota.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnAnggota.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_lineAnggota.setBackground(new java.awt.Color(236, 239, 241));
        pn_lineAnggota.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_lineAnggotaLayout = new javax.swing.GroupLayout(pn_lineAnggota);
        pn_lineAnggota.setLayout(pn_lineAnggotaLayout);
        pn_lineAnggotaLayout.setHorizontalGroup(
            pn_lineAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_lineAnggotaLayout.setVerticalGroup(
            pn_lineAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/People_2.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_anggota.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_anggota.setForeground(new java.awt.Color(102, 102, 102));
        btn_anggota.setText("Anggota");
        btn_anggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_anggota.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnAnggotaLayout = new javax.swing.GroupLayout(pn_btnAnggota);
        pn_btnAnggota.setLayout(pn_btnAnggotaLayout);
        pn_btnAnggotaLayout.setHorizontalGroup(
            pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnAnggotaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnAnggotaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnAnggotaLayout.setVerticalGroup(
            pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnAnggotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnAnggotaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_btnBuku.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnBuku.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_lineBuku.setBackground(new java.awt.Color(236, 239, 241));
        pn_lineBuku.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_lineBukuLayout = new javax.swing.GroupLayout(pn_lineBuku);
        pn_lineBuku.setLayout(pn_lineBukuLayout);
        pn_lineBukuLayout.setHorizontalGroup(
            pn_lineBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_lineBukuLayout.setVerticalGroup(
            pn_lineBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Books.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_buku.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_buku.setForeground(new java.awt.Color(102, 102, 102));
        btn_buku.setText("Buku");
        btn_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buku.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bukuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnBukuLayout = new javax.swing.GroupLayout(pn_btnBuku);
        pn_btnBuku.setLayout(pn_btnBukuLayout);
        pn_btnBukuLayout.setHorizontalGroup(
            pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnBukuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnBukuLayout.setVerticalGroup(
            pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnBukuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_btnKategori.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnKategori.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_lineKategori.setBackground(new java.awt.Color(236, 239, 241));
        pn_lineKategori.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_lineKategoriLayout = new javax.swing.GroupLayout(pn_lineKategori);
        pn_lineKategori.setLayout(pn_lineKategoriLayout);
        pn_lineKategoriLayout.setHorizontalGroup(
            pn_lineKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_lineKategoriLayout.setVerticalGroup(
            pn_lineKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Diversity.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_kategori.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_kategori.setForeground(new java.awt.Color(102, 102, 102));
        btn_kategori.setText("Kategori");
        btn_kategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kategori.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kategoriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kategoriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kategoriMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnKategoriLayout = new javax.swing.GroupLayout(pn_btnKategori);
        pn_btnKategori.setLayout(pn_btnKategoriLayout);
        pn_btnKategoriLayout.setHorizontalGroup(
            pn_btnKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnKategoriLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnKategoriLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnKategoriLayout.setVerticalGroup(
            pn_btnKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnKategoriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnKategoriLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_btnPenerbit.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnPenerbit.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_linePenerbit.setBackground(new java.awt.Color(236, 239, 241));
        pn_linePenerbit.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_linePenerbitLayout = new javax.swing.GroupLayout(pn_linePenerbit);
        pn_linePenerbit.setLayout(pn_linePenerbitLayout);
        pn_linePenerbitLayout.setHorizontalGroup(
            pn_linePenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_linePenerbitLayout.setVerticalGroup(
            pn_linePenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Literature.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_penerbit.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_penerbit.setForeground(new java.awt.Color(102, 102, 102));
        btn_penerbit.setText("Penerbit");
        btn_penerbit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_penerbit.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_penerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penerbitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_penerbitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_penerbitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPenerbitLayout = new javax.swing.GroupLayout(pn_btnPenerbit);
        pn_btnPenerbit.setLayout(pn_btnPenerbitLayout);
        pn_btnPenerbitLayout.setHorizontalGroup(
            pn_btnPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPenerbitLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPenerbitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnPenerbitLayout.setVerticalGroup(
            pn_btnPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPenerbitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPenerbitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_btnPetugas.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnPetugas.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_linePetugas.setBackground(new java.awt.Color(236, 239, 241));
        pn_linePetugas.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_linePetugasLayout = new javax.swing.GroupLayout(pn_linePetugas);
        pn_linePetugas.setLayout(pn_linePetugasLayout);
        pn_linePetugasLayout.setHorizontalGroup(
            pn_linePetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_linePetugasLayout.setVerticalGroup(
            pn_linePetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/User.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_petugas.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_petugas.setForeground(new java.awt.Color(102, 102, 102));
        btn_petugas.setText("Petugas");
        btn_petugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_petugas.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_petugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_petugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_petugasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPetugasLayout = new javax.swing.GroupLayout(pn_btnPetugas);
        pn_btnPetugas.setLayout(pn_btnPetugasLayout);
        pn_btnPetugasLayout.setHorizontalGroup(
            pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPetugasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPetugasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnPetugasLayout.setVerticalGroup(
            pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPetugasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPetugasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lb_master, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pn_btnDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_btnAnggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_btnBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_btnKategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_btnPetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_btnPenerbit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_master)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        pn_btnDashboard.setBackground(new Color(240, 240, 240));
        pn_line.setBackground(new Color(55, 71, 79));
        
        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Dashboard());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        pn_btnDashboard.setBackground(new Color(250, 250, 250));
        pn_line.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        pn_btnDashboard.setBackground(new Color(236, 239, 241));
        pn_line.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseClicked
        // TODO add your handling code here:
        pn_btnAnggota.setBackground(new Color(240, 240, 240));
        pn_lineAnggota.setBackground(new Color(55, 71, 79));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Anggota());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_anggotaMouseClicked

    private void btn_anggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseEntered
        // TODO add your handling code here:
        pn_btnAnggota.setBackground(new Color(250, 250, 250));
        pn_lineAnggota.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_anggotaMouseEntered

    private void btn_anggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseExited
        // TODO add your handling code here:
        pn_btnAnggota.setBackground(new Color(236, 239, 241));
        pn_lineAnggota.setBackground(new Color(236, 239, 241));

    }//GEN-LAST:event_btn_anggotaMouseExited

    private void btn_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseClicked
        // TODO add your handling code here:
        pn_btnBuku.setBackground(new Color(240, 240, 240));
        pn_lineBuku.setBackground(new Color(55, 71, 79));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Buku());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_bukuMouseClicked

    private void btn_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseEntered
        // TODO add your handling code here:
        pn_btnBuku.setBackground(new Color(250, 250, 250));
        pn_lineBuku.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_bukuMouseEntered

    private void btn_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseExited
        // TODO add your handling code here:
        pn_btnBuku.setBackground(new Color(236, 239, 241));
        pn_lineBuku.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_btn_bukuMouseExited

    private void btn_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kategoriMouseClicked
        // TODO add your handling code here:
        pn_btnKategori.setBackground(new Color(240, 240, 240));
        pn_lineKategori.setBackground(new Color(55, 71, 79));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Kategori());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_kategoriMouseClicked

    private void btn_kategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kategoriMouseEntered
        // TODO add your handling code here:
        pn_btnKategori.setBackground(new Color(250, 250, 250));
        pn_lineKategori.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_kategoriMouseEntered

    private void btn_kategoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kategoriMouseExited
        // TODO add your handling code here:
        pn_btnKategori.setBackground(new Color(236, 239, 241));
        pn_lineKategori.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_btn_kategoriMouseExited

    private void btn_penerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penerbitMouseClicked
        // TODO add your handling code here:
        pn_btnPenerbit.setBackground(new Color(240, 240, 240));
        pn_linePenerbit.setBackground(new Color(55, 71, 79));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Penerbit());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_penerbitMouseClicked

    private void btn_penerbitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penerbitMouseEntered
        // TODO add your handling code here:
        pn_btnPenerbit.setBackground(new Color(250, 250, 250));
        pn_linePenerbit.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_penerbitMouseEntered

    private void btn_penerbitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penerbitMouseExited
        // TODO add your handling code here:
        pn_btnPenerbit.setBackground(new Color(236, 239, 241));
        pn_linePenerbit.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_btn_penerbitMouseExited

    private void btn_petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseClicked
        // TODO add your handling code here:
        pn_btnPetugas.setBackground(new Color(240, 240, 240));
        pn_linePetugas.setBackground(new Color(55, 71, 79));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Petugas());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_petugasMouseClicked

    private void btn_petugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseEntered
        // TODO add your handling code here:
        pn_btnPetugas.setBackground(new Color(250, 250, 250));
        pn_linePetugas.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_petugasMouseEntered

    private void btn_petugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseExited
        // TODO add your handling code here:
        pn_btnPetugas.setBackground(new Color(236, 239, 241));
        pn_linePetugas.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_btn_petugasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_anggota;
    private javax.swing.JLabel btn_buku;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_kategori;
    private javax.swing.JLabel btn_penerbit;
    private javax.swing.JLabel btn_petugas;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb_master;
    private javax.swing.JPanel pn_btnAnggota;
    private javax.swing.JPanel pn_btnBuku;
    private javax.swing.JPanel pn_btnDashboard;
    private javax.swing.JPanel pn_btnKategori;
    private javax.swing.JPanel pn_btnPenerbit;
    private javax.swing.JPanel pn_btnPetugas;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_lineAnggota;
    private javax.swing.JPanel pn_lineBuku;
    private javax.swing.JPanel pn_lineKategori;
    private javax.swing.JPanel pn_linePenerbit;
    private javax.swing.JPanel pn_linePetugas;
    // End of variables declaration//GEN-END:variables
}
