/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import View.Dashboard;
import View.FormLogin;
import View.Peminjaman;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author YANUAREKA
 */
public class MenuUtama1 extends javax.swing.JFrame {
    Timer updateTimer;
    int Delay = 100;

    private String menuUtama;
    private String userId;
    private String levelUser;
    
    public MenuUtama1(String userId, String levelUser, String user) {
        initComponents();
        
        //Set jframe menjadi ukuran maximal
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.menuUtama = menuUtama;
        this.userId = userId;
        this.levelUser = levelUser;
        
        addMenu();
        
        updateTimer = new Timer(Delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date currentDate = new Date();
                // Menambahkan Objek SimpleDateFormat dengan format tanggal Indonesia
                SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, dd-MM-yyyy  HH:mm:ss", new Locale("id", "ID"));

                // SimpleDateFormat untuk mengubah tanggal menjadi string
                String formattedDate = dateFormat.format(currentDate);
               
               dateLb.setText(formattedDate);
            }
        });
        updateTimer.start();
        
        loginAsLevel.setText(levelUser);
        lbUsername.setText(user);
    }
    
    //Getter
    public String getUserId() {
        return userId;
    }
    public String getLevelUser() {
        return levelUser;
    }
    public JPanel getPanelUtama(){
        return pn_mainContent;
    }
    
    private void addMenu(){
        if(levelUser.equals("Admin")){
            sideMenu.add(new MasterData(this));
            sideMenu.add(new Transaksi(this));
        } else {
            sideMenu.add(new Transaksi(this));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_side = new javax.swing.JPanel();
        textBrandIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sideMenu = new javax.swing.JPanel();
        pn_main = new javax.swing.JPanel();
        pn_top = new javax.swing.JPanel();
        dateLb = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        loginAs = new javax.swing.JLabel();
        loginAsLevel = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();
        pn_mainContent = new javax.swing.JPanel();
        panelHero = new javax.swing.JPanel();
        lbUsername = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCTA = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_side.setBackground(new java.awt.Color(236, 239, 241));
        pn_side.setPreferredSize(new java.awt.Dimension(250, 646));

        textBrandIcon.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        textBrandIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBrandIcon.setText("LIBRARYNEW");
        textBrandIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBrandIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBrandIconMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Shop_2.png"))); // NOI18N

        jScrollPane1.setBorder(null);

        sideMenu.setBackground(new java.awt.Color(236, 239, 241));
        sideMenu.setLayout(new javax.swing.BoxLayout(sideMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(sideMenu);

        javax.swing.GroupLayout pn_sideLayout = new javax.swing.GroupLayout(pn_side);
        pn_side.setLayout(pn_sideLayout);
        pn_sideLayout.setHorizontalGroup(
            pn_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sideLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBrandIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(pn_sideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_sideLayout.setVerticalGroup(
            pn_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sideLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pn_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBrandIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pn_side, java.awt.BorderLayout.LINE_START);

        pn_main.setLayout(new java.awt.BorderLayout());

        pn_top.setBackground(new java.awt.Color(236, 239, 241));
        pn_top.setPreferredSize(new java.awt.Dimension(972, 80));

        dateLb.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        dateLb.setForeground(new java.awt.Color(153, 153, 153));
        dateLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLb.setText("DD:MM:YYYY");
        dateLb.setPreferredSize(new java.awt.Dimension(106, 25));

        btnLogout.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 102, 102));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logout_1.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setPreferredSize(new java.awt.Dimension(38, 25));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        loginAs.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        loginAs.setForeground(new java.awt.Color(153, 153, 153));
        loginAs.setText("Login as : ");

        loginAsLevel.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        loginAsLevel.setForeground(new java.awt.Color(102, 102, 102));
        loginAsLevel.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout pn_topLayout = new javax.swing.GroupLayout(pn_top);
        pn_top.setLayout(pn_topLayout);
        pn_topLayout.setHorizontalGroup(
            pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_topLayout.createSequentialGroup()
                .addContainerGap(822, Short.MAX_VALUE)
                .addGroup(pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLb, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_topLayout.createSequentialGroup()
                        .addComponent(loginAs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginAsLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_topLayout.setVerticalGroup(
            pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginAsLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginAs))
                .addGap(18, 18, 18)
                .addComponent(dateLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_main.add(pn_top, java.awt.BorderLayout.PAGE_START);

        pn_content.setBackground(new java.awt.Color(255, 255, 255));

        pn_mainContent.setBackground(new java.awt.Color(255, 255, 255));
        pn_mainContent.setLayout(new java.awt.BorderLayout());

        panelHero.setBackground(new java.awt.Color(255, 255, 255));

        lbUsername.setFont(new java.awt.Font("Poppins Light", 0, 48)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(102, 102, 102));
        lbUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbUsername.setPreferredSize(new java.awt.Dimension(137, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/books-hero.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 44)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Library of the future");
        jLabel5.setPreferredSize(new java.awt.Dimension(137, 70));

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Hello, ");
        jLabel6.setPreferredSize(new java.awt.Dimension(137, 70));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 44)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Welcome to the");
        jLabel7.setPreferredSize(new java.awt.Dimension(137, 70));

        btnCTA.setBackground(new java.awt.Color(55, 71, 79));
        btnCTA.setText("let's started");
        btnCTA.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        btnCTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeroLayout = new javax.swing.GroupLayout(panelHero);
        panelHero.setLayout(panelHeroLayout);
        panelHeroLayout.setHorizontalGroup(
            panelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeroLayout.createSequentialGroup()
                .addGroup(panelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeroLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCTA, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHeroLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeroLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(946, Short.MAX_VALUE)))
        );
        panelHeroLayout.setVerticalGroup(
            panelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeroLayout.createSequentialGroup()
                .addGroup(panelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeroLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(panelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeroLayout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );

        pn_mainContent.add(panelHero, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_main.add(pn_content, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah yakin ingin keluar?",
                "Konfirmasi keluar",
                JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION) {     
            FormLogin login = new FormLogin();
            login.setVisible(true);
            login.revalidate();

            dispose();
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnCTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTAActionPerformed
        // TODO add your handling code here:
        //Validasi akses login
        if(levelUser.equals("Admin")) {
            pn_mainContent.removeAll();
            pn_mainContent.add(new Dashboard());
            pn_mainContent.repaint();
            pn_mainContent.revalidate();
        } else {
            pn_mainContent.removeAll();
            pn_mainContent.add(new Peminjaman(getUserId()));
            pn_mainContent.repaint();
            pn_mainContent.revalidate();
        }
    }//GEN-LAST:event_btnCTAActionPerformed

    private void textBrandIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBrandIconMouseClicked
        // TODO add your handling code here:
        pn_mainContent.removeAll();
        pn_mainContent.add(panelHero);
        pn_mainContent.repaint();
        pn_mainContent.revalidate();
    }//GEN-LAST:event_textBrandIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Setup library FlatLight
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String userId = "id_user";
                String levelUser = "level";
                String username = "username";
                new MenuUtama1(userId, levelUser, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnCTA;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel dateLb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel loginAs;
    private javax.swing.JLabel loginAsLevel;
    private javax.swing.JPanel panelHero;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_mainContent;
    private javax.swing.JPanel pn_side;
    private javax.swing.JPanel pn_top;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JLabel textBrandIcon;
    // End of variables declaration//GEN-END:variables
}
