/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import View.Peminjaman;
import View.Pengembalian;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author YANUAREKA
 */
public class Transaksi extends javax.swing.JPanel {

    private MenuUtama1 menuUtama;
    
    public Transaksi(MenuUtama1 menuUtama) {
        initComponents();
        this.menuUtama = menuUtama;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_transaksi = new javax.swing.JLabel();
        pn_btnPeminjaman = new javax.swing.JPanel();
        pn_linePeminjaman = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_peminjaman = new javax.swing.JLabel();
        pn_btnPengembalian = new javax.swing.JPanel();
        pn_linePengembalian = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_pengembalian = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 239, 241));

        lb_transaksi.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lb_transaksi.setForeground(new java.awt.Color(204, 204, 204));
        lb_transaksi.setText("Transaksi");

        pn_btnPeminjaman.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnPeminjaman.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_linePeminjaman.setBackground(new java.awt.Color(236, 239, 241));
        pn_linePeminjaman.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_linePeminjamanLayout = new javax.swing.GroupLayout(pn_linePeminjaman);
        pn_linePeminjaman.setLayout(pn_linePeminjamanLayout);
        pn_linePeminjamanLayout.setHorizontalGroup(
            pn_linePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_linePeminjamanLayout.setVerticalGroup(
            pn_linePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Health Book_2.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_peminjaman.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_peminjaman.setForeground(new java.awt.Color(102, 102, 102));
        btn_peminjaman.setText("Peminjaman");
        btn_peminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_peminjaman.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPeminjamanLayout = new javax.swing.GroupLayout(pn_btnPeminjaman);
        pn_btnPeminjaman.setLayout(pn_btnPeminjamanLayout);
        pn_btnPeminjamanLayout.setHorizontalGroup(
            pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPeminjamanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPeminjamanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnPeminjamanLayout.setVerticalGroup(
            pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPeminjamanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPeminjamanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_btnPengembalian.setBackground(new java.awt.Color(236, 239, 241));
        pn_btnPengembalian.setPreferredSize(new java.awt.Dimension(223, 45));

        pn_linePengembalian.setBackground(new java.awt.Color(236, 239, 241));
        pn_linePengembalian.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout pn_linePengembalianLayout = new javax.swing.GroupLayout(pn_linePengembalian);
        pn_linePengembalian.setLayout(pn_linePengembalianLayout);
        pn_linePengembalianLayout.setHorizontalGroup(
            pn_linePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_linePengembalianLayout.setVerticalGroup(
            pn_linePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Return Book_1.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(35, 35));

        btn_pengembalian.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_pengembalian.setForeground(new java.awt.Color(102, 102, 102));
        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengembalian.setPreferredSize(new java.awt.Dimension(58, 35));
        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPengembalianLayout = new javax.swing.GroupLayout(pn_btnPengembalian);
        pn_btnPengembalian.setLayout(pn_btnPengembalianLayout);
        pn_btnPengembalianLayout.setHorizontalGroup(
            pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPengembalianLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPengembalianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        pn_btnPengembalianLayout.setVerticalGroup(
            pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPengembalianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPengembalianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linePengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_btnPeminjaman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lb_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_btnPengembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_transaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseClicked
        // TODO add your handling code here:
        pn_btnPeminjaman.setBackground(new Color(240, 240, 240));
        pn_linePeminjaman.setBackground(new Color(55, 71, 79));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Peminjaman(menuUtama.getUserId()));
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_peminjamanMouseClicked

    private void btn_peminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseEntered
        // TODO add your handling code here:
        pn_btnPeminjaman.setBackground(new Color(250, 250, 250));
        pn_linePeminjaman.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_peminjamanMouseEntered

    private void btn_peminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseExited
        // TODO add your handling code here:
        pn_btnPeminjaman.setBackground(new Color(236, 239, 241));
        pn_linePeminjaman.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_btn_peminjamanMouseExited

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:
        pn_btnPengembalian.setBackground(new Color(240, 240, 240));
        pn_linePengembalian.setBackground(new Color(55, 71, 79));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new Pengembalian(menuUtama.getUserId()));
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_pengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseEntered
        // TODO add your handling code here:
        pn_btnPengembalian.setBackground(new Color(250, 250, 250));
        pn_linePengembalian.setBackground(new Color(55, 71, 79));
    }//GEN-LAST:event_btn_pengembalianMouseEntered

    private void btn_pengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseExited
        // TODO add your handling code here:
        pn_btnPengembalian.setBackground(new Color(236, 239, 241));
        pn_linePengembalian.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_btn_pengembalianMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_peminjaman;
    private javax.swing.JLabel btn_pengembalian;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_transaksi;
    private javax.swing.JPanel pn_btnPeminjaman;
    private javax.swing.JPanel pn_btnPengembalian;
    private javax.swing.JPanel pn_linePeminjaman;
    private javax.swing.JPanel pn_linePengembalian;
    // End of variables declaration//GEN-END:variables
}
